---
title: "EDS 223: Homework 1"
subtitle: "Evaluating the Respiratory Health Index For Puerto Rico and Hawaii"
author: "Nathalie Bonnet"
date: 2025-10-6
format: 
  pdf:
    documentclass: report
warning: FALSE
---

```{r}
# Read in necessary libraries
library(tidyverse)
library(sf)
library(here)
library(tmap)
```


```{r}
# read in geodatabase of EJScreen data at the Census Block Group level
ejscreen <- sf::st_read(here::here("data", "ejscreen","EJSCREEN_2023_BG_StatePct_with_AS_CNMI_GU_VI.gdb")) 

```


```{r}
# Creating a subset to explore data on % low income by state 
mean_low_income <- ejscreen %>% 
  group_by(STATE_NAME) %>% 
  summarise(mean_percent_low_income = mean(LOWINCPCT)) %>% 
  drop_na(mean_percent_low_income)
```


```{r}
# Finding the states/ territories with the lowest average percent low income
lowest_mean_poverty <- mean_low_income %>%
  slice_min(mean_percent_low_income, n = 5) %>%
  select(STATE_NAME, mean_percent_low_income)

# Showing the state/territory with the lowest average low income percentage
head(lowest_mean_poverty, 3) 
```

```{r}
# Finding the states/ territories with the highest average percent low income
highest_mean_poverty <- mean_low_income %>%
  slice_max(mean_percent_low_income, n = 5) %>%
  select(STATE_NAME, mean_percent_low_income)

# Showing the state/territory with the highest average low income percentage
head(highest_mean_poverty, 1) 
```



```{r}
# Filtering for only observation in Hawaii
hawaii <- ejscreen %>%
  filter(STATE_NAME == "Hawaii") %>% 
  filter(ACSTOTPOP > 0)
```

```{r}
# Filtering for only observations in Puerto Rico
puerto_rico <- ejscreen %>%
  filter(STATE_NAME == "Puerto Rico") %>% 
  filter(ACSTOTPOP > 0)
```

```{r}
sf::st_geometry(puerto_rico)
```


```{r}

tm_shape(puerto_rico) +
  tm_crs(4326)+ 
  
  tm_polygons(fill = "RESP", 
              fill.scale = tm_scale(values = c("#FFEBE6", "#FF9C80", 
                                               "#FF5B2E", "#D12D00", 
                                               "#751900"), 
                                    breaks = c(0, 0.1, 0.2, 0.3, 0.4, 0.5)), 
              fill.legend = tm_legend(title = "Respiratory HI",
                                      tm_pos_out = "right"), 
             lty = "blank", 
              size = 2) +
  tm_graticules() +
  tm_title("Respiratory Health Index Values in Puerto Rico") +
  tm_layout(bg.color = "lightblue") 
  
```
```{r}
tm_shape(hawaii) + 
  tm_crs(4326)+ 
  tm_graticules() +
  tm_polygons(fill = "RESP", 
              fill.scale = tm_scale(values = c("#FFEBE6",
                                               "#FF9C80",
                                               "#FF5B2E",
                                               "#D12D00",
                                               "#751900", 
                                               "#8AEA92", 
                                               "#80ADA0",
                                               "#5F5566", 
                                               "#583748", 
                                               "#000000"), 
                                    breaks = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1)), fill.legend = tm_legend(title = "Respiratory HI", tm_pos_out = "right"), lty = "blank", size = 2) + tm_title("Respiratory Health Index Values in Hawaii") + 
  tm_layout(bg.color = "lightblue")
```

